name: prayer_time
description: "A new Flutter project."
publish_to: 'none'

version: 0.5.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flutter_localization: ^0.3.3
  go_router: ^16.3.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  shared_preferences: ^2.5.3
  dio: ^5.9.0
  geolocator: ^13.0.2
  geocoding: ^4.0.0
  bloc: ^9.1.0
  table_calendar: ^3.2.0
  flutter_qiblah: ^3.1.0+1
  flutter_compass_v2: ^1.0.3
  app_settings: ^6.1.1
  permission_handler: ^12.0.1
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  flutter_background_service: ^5.1.0
  flutter_native_splash: ^2.4.7
  camera: ^0.11.2+1
  flutter_svg: ^2.2.3
  get_it: ^9.1.1
  flutter_phoenix: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



flutter_native_splash:
  color: "#ffe5c8"
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true
  generate: true

  
  assets:
    - assets/splashScreen/